#include "Code_Generation/Code_Generation.hpp"
// #include "Misc.hpp"
#include "Config/config.h"
#include <string>
#include <fstream>
#include <filesystem>

/* TODO:
 * Add a simple ORCC compatibility that was copied from the code generated by ORCC.
 * This allows the use the ORCC demo projects for testing.
 */
std::string parse_command_line_input_function_rust = "";

std::string header_rust = "";

std::pair<std::string, std::string> generate_ORCC_compatibility_layer_rust(std::string path)
{
	Config* c = c->getInstance();
	{
		std::filesystem::path tmp{ path };
		tmp /= "options.rs";
		std::ofstream output_file{ tmp };
		if (output_file.fail())
		{
			throw Code_Generation::Code_Generation_Exception{ "Cannot open the file " + tmp.string() };
		}
		output_file << header_rust;
		output_file.close();
	}
	std::filesystem::path tmp{ path };
	std::string filename;

	filename = "orcc_compatibility.rs";
	tmp /= filename;

	std::ofstream source_file{ tmp };
	if (source_file.fail())
	{
		throw Code_Generation::Code_Generation_Exception{ "Cannot open file " + tmp.string() };
	}

	source_file << parse_command_line_input_function_rust;
	source_file.close();

	return std::make_pair("options.rs", filename);
}